title: Hackersden Writeup Series.
description: A collection of awesome write-ups of Infosec.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one